<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE students
[<!ELEMENT students (student)*>
<!ELEMENT student   (name, age, specialty, grade)>
<!ELEMENT name      (#PCDATA)>
<!ELEMENT age       (#PCDATA)>
<!ELEMENT specialty (#PCDATA)>
<!ELEMENT grade     (#PCDATA)>
]>
<students>
    <student>
        <name>장신원</name>
        <age>24</age>
        <specialty>컴퓨터과학과</specialty>
        <grade>3</grade>
    </student>
    <student>
        <name>조정헌</name>
        <age>23</age>
        <specialty>국어국문학</specialty>
        <grade>3</grade>
    </student>
</students>
