<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE BookCatalog
[<!ELEMENT BookCatalog  (Book)*>
<!ELEMENT Book          (Title, Author, Year)>
<!ELEMENT Title         (#PCDATA)>
<!ELEMENT Author        (#PCDATA)>
<!ELEMENT Year          (#PCDATA)>
]>
<BookCatalog>
    <Book>
        <Title>new ideas from dead economists</Title>
        <Author>Todd G. Buchholz</Author>
        <Year>2007</Year>
        <Summary> <![CDATA[현대 경제사상의 이해를 위한 입문서]]> </Summary>
    </Book>
    <Book>
        <Title>Pensées</Title>
        <Author>Blaise Pascal</Author>
        <Year>1670</Year>
        <Summary> <![CDATA[기독교의 논리적 철학적 변증서]]> </Summary>
    </Book>
    <Book>
        <Title>Zero to One</Title>
        <Author>Peter Thiel</Author>
        <Year>2014</Year>
        <Summary> <![CDATA[스탠퍼드 대학교 스타트업 최고 명강의]]> </Summary>
    </Book>
    <Book>
        <Title>Gang Leader for a Day</Title>
        <Author>Sudhir Venkatesh</Author>
        <Year>2008</Year>
        <Summary> <![CDATA[통계와 연구실을 박차고 거리로 나선 괴짜 사회학자의 세상탐구]]> </Summary>
    </Book>
</BookCatalog>
