=== jdentity/webFramework/Youtube.xsd
<?xml version="1.0" encoding="utf-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://cs.skuniv.ac.kr/xml/jsw"
    xmlns:target="http://cs.skuniv.ac.kr/xml/jsw"
    elementFormDefault="qualified">

    <simpleType name="CategoryRestriction">
        <restriction base="string">
            <enumeration value="AutoVehicles" />
            <enumeration value="Comedy" />
            <enumeration value="Education" />
            <enumeration value="Entertainment" />
            <enumeration value="Film" />
            <enumeration value="Gaming" />
            <enumeration value="HowtoStyle" />
            <enumeration value="Music" />
            <enumeration value="NewsPolitics" />
            <enumeration value="NonprofitActivism" />
            <enumeration value="PeopleBlogs" />
            <enumeration value="PetsAnimal" />
            <enumeration value="ScienceTechnology" />
            <enumeration value="Shows" />
            <enumeration value="Sports" />
            <enumeration value="Travel" />
            <enumeration value="Fashion" />
            <enumeration value="Etc" />
        </restriction>
    </simpleType>

    <group name="EarningGroup" >
        <sequence>
            <element name="min" type="string" />
            <element name="max" type="string" />
        </sequence>
    </group>

    <attributeGroup name="EarningAttribute">
        <attribute name="period" type="string" />
        <attribute name="currency" type="string" />
    </attributeGroup>

    <complexType name="EarningType">
        <group ref="target:EarningGroup" />
        <attributeGroup ref="target:EarningAttribute"/>
    </complexType>

    <group name="VideoGroup">
        <sequence>
            <element name="title" type="string" />
            <element name="uploadDate" type="date" />
            <element name="views" type="string" />
            <element name="likes" type="string" />
            <element name="unlikes" type="string" />
            <element name="comments" type="string" />
            <element name="link" type="anyURI" /> 
        </sequence>
    </group>

    <complexType name="VideoType">
        <group ref="target:VideoGroup" />
    </complexType>

    <group name="ChannelGroup">
        <sequence>
            <element name="Name" type="string" />
            <element name="Rank" type="positiveInteger" />
            <element name="Category" maxOccurs="3" type="target:CategoryRestriction" />
            <element name="SignUpDate" type="date" />
            <element name="Subscribers" type="string" />
            <element name="TotalViews" type="string" />
            <element name="AverageViews" type="string" />
            <element name="Videos" type="string" />
            <element name="PotentialEarnings" type="target:EarningType"/>
            <element name="BestVideo" maxOccurs="1" type="target:VideoType" />
        </sequence>
    </group>

    <attributeGroup name="ChannelAttribute">
        <attribute name="area" type="string" use="required"/>
        <attribute name="language" type="string" default="English"/>
    </attributeGroup>

    <complexType name="ChannelType">
        <group ref="target:ChannelGroup" />
        <attributeGroup ref="target:ChannelAttribute" />
    </complexType>

    <element name="Youtube">
        <complexType>
            <choice maxOccurs="unbounded">
                <element name="Channel" type="target:ChannelType" />
            </choice>
        </complexType>
    </element>
</schema>

=== jdentity/webFramework/Youtube.xml
<?xml version="1.0" encoding="utf-8"?>
<Youtube xmlns="http://cs.skuniv.ac.kr/xml/jsw"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://cs.skuniv.ac.kr/xml/jsw Youtube.xsd">
    <Channel area="India" language="English">
        <Name> T-Series </Name>
        <Rank> 1 </Rank>
        <Category>Music</Category>
        <SignUpDate> 2006-03-13 </SignUpDate>
        <Subscribers> 158M </Subscribers>
        <TotalViews> 129.3B </TotalViews>
        <AverageViews> 3.62M </AverageViews>
        <Videos> 14.74K </Videos>
        <PotentialEarnings period="monthly" currency="$">
            <min>585.24K</min>
            <max>1.56M</max>
        </PotentialEarnings>
        <BestVideo>
            <title>Meri Aashiqui Song | Rochak Kohli Feat. Jubin Nautiyal | Ihana D | Shree Anwar Sagar | Bhushan Kumar</title>
            <uploadDate> 2020-06-03 </uploadDate>
            <views> 97.64M </views>
            <likes> 1.76M </likes>
            <unlikes> 70.58K </unlikes>
            <comments> 61.71K </comments>
            <link> https://www.youtube.com/watch?v=SVjkxdjivts&amp;feature=emb_title&amp;ab_channel=T-Series </link>
        </BestVideo>
    </Channel>
    <Channel area="United States" language="English">
        <Name> PewDiePie </Name>
        <Rank> 2 </Rank>
        <Category>Gaming</Category>
        <Category>Entertainment</Category>
        <SignUpDate> 2010-04-29 </SignUpDate>
        <Subscribers> 107M </Subscribers>
        <TotalViews> 26.28B </TotalViews>
        <AverageViews> 6.03M </AverageViews>
        <Videos> 4.22K </Videos>
        <PotentialEarnings period="monthly" currency="$">
            <min>372.73K</min>
            <max>1.15M</max>
        </PotentialEarnings>
        <BestVideo>
            <title> It's been real, but I'm out! - LWIAY #00106 </title>
            <uploadDate> 2020-01-15 </uploadDate>
            <views> 24.22M </views>
            <likes> 1.86M </likes>
            <unlikes> 25.56K </unlikes>
            <comments> 180.85K </comments>
            <link> https://www.youtube.com/watch?v=IZXgjR9INsA&amp;feature=emb_title&amp;ab_channel=PewDiePie </link>
        </BestVideo>
    </Channel>
    <Channel area="United States" language="English">
        <Name> Cocomelon - Nursery Rhymes </Name>
        <Rank> 3 </Rank>
        <Category>Education</Category>
        <SignUpDate> 2006-09-01 </SignUpDate>
        <Subscribers> 96.7M </Subscribers>
        <TotalViews> 81.76B </TotalViews>
        <AverageViews> 38.35M </AverageViews>
        <Videos> 574 </Videos>
        <PotentialEarnings period="monthly" currency="$">
            <min>6.12M</min>
            <max>18.95M</max>
        </PotentialEarnings>
        <BestVideo>
            <title> Deck the Halls - Christmas Song for Kids | CoCoMelon Nursery Rhymes &amp; Kids Songs </title>
            <uploadDate> 2018-12-11 </uploadDate>
            <views> 679.81M </views>
            <likes> 363.81K </likes>
            <unlikes> 185.33K </unlikes>
            <comments> 2.97K </comments>
            <link> https://www.youtube.com/watch?v=Y2T_rIZ4Pho&amp;feature=emb_title </link>
        </BestVideo>
    </Channel>
    <Channel area="India" language="English">
        <Name> SET India </Name>
        <Rank> 4 </Rank>
        <Category>Entertainment</Category>
        <SignUpDate> 2006-09-20 </SignUpDate>
        <Subscribers> 86.3M </Subscribers>
        <TotalViews> 69.62B </TotalViews>
        <AverageViews> 19.04K </AverageViews>
        <Videos> 43.38K </Videos>
        <PotentialEarnings period="monthly" currency="$">
            <min>436.1K</min>
            <max>1.16M</max>
        </PotentialEarnings>
        <BestVideo>
            <title> Akshit's Performance Leaves Sushant, Bhumi &amp; Judges Teary-eyed | Super Dancer Chapter 3 </title>
            <uploadDate> 2020-06-17 </uploadDate>
            <views> 16.91M </views>
            <likes> 364.5K </likes>
            <unlikes> 16.41K </unlikes>
            <comments> 10.32K </comments>
            <link> https://www.youtube.com/watch?v=mAwgoXxXPAw&amp;feature=emb_title </link>
        </BestVideo>
    </Channel>
    <Channel area="United States" language="English">
        <Name> 5-Minute Crafts </Name>
        <Rank> 5 </Rank>
        <Category>HowtoStyle</Category>
        <SignUpDate> 2016-11-15 </SignUpDate>
        <Subscribers> 69.1M </Subscribers>
        <TotalViews> 18.81B </TotalViews>
        <AverageViews> 2.5M </AverageViews>
        <Videos> 4.61K </Videos>
        <PotentialEarnings period="monthly" currency="$">
            <min>351.56K</min>
            <max>1.08M</max>
        </PotentialEarnings>
        <BestVideo>
            <title>26 PRICELESS HACKS FOR PARENTS</title>
            <uploadDate> 2020-03-11 </uploadDate>
            <views> 16.82M </views>
            <likes> 106.88K </likes>
            <unlikes> 23.18K </unlikes>
            <comments> 3.19K </comments>
            <link> https://www.youtube.com/watch?v=93dIviz82JU </link>
        </BestVideo>
    </Channel>
    <Channel area="United States" language="English">
        <Name> WWE </Name>
        <Rank> 6 </Rank>
        <Category>Sports</Category>
        <SignUpDate> 2007-05-10 </SignUpDate>
        <Subscribers> 68.2M </Subscribers>
        <TotalViews> 50.57B </TotalViews>
        <AverageViews> 281.97K </AverageViews>
        <Videos> 50.47K </Videos>
        <PotentialEarnings period="monthly" currency="$">
            <min>2.2M</min>
            <max>6.81M</max>
        </PotentialEarnings>
        <BestVideo>
            <title>FULL MATCH - Big Show vs. The Great Khali: Backlash 2008</title>
            <uploadDate> 2020-04-22 </uploadDate>
            <views> 7.73M </views>
            <likes> 119.13K </likes>
            <unlikes> 13.33K </unlikes>
            <comments> 5.36K </comments>
            <link> https://www.youtube.com/watch?v=0R-pFCyOuSE&amp;feature=emb_title </link>
        </BestVideo>
    </Channel>
    <Channel area="United States" language="English">
        <Name> ✿ Kids Diana Show </Name>
        <Rank> 7 </Rank>
        <Category>Entertainment</Category>
        <SignUpDate> 2015-05-12 </SignUpDate>
        <Subscribers> 66.5M </Subscribers>
        <TotalViews> 42.28B </TotalViews>
        <AverageViews> 16.36M </AverageViews>
        <Videos> 771 </Videos>
        <PotentialEarnings period="monthly" currency="$">
            <min>4.79M</min>
            <max>14.82M</max>
        </PotentialEarnings>
        <BestVideo>
            <title>Diana Pretend Play with Princess Carriage Inflatable Toy</title>
            <uploadDate> 2019-01-13 </uploadDate>
            <views> 760.09M </views>
            <likes> 710.97K </likes>
            <unlikes> 324.42K </unlikes>
            <comments> 0 </comments>
            <link> https://www.youtube.com/watch?v=ZlxIEWygQYY&amp;feature=emb_title </link>
        </BestVideo>
    </Channel>
    <Channel area="India" language="English">
        <Name> Zee Music Company </Name>
        <Rank> 8 </Rank>
        <Category>Music</Category>
        <SignUpDate> 2014-03-12 </SignUpDate>
        <Subscribers> 63.6M </Subscribers>
        <TotalViews> 30.72B </TotalViews>
        <AverageViews> 2.04M </AverageViews>
        <Videos> 5.03K </Videos>
        <PotentialEarnings period="monthly" currency="$">
            <min>133.74K</min>
            <max>356.65K</max>
        </PotentialEarnings>
        <BestVideo>
            <title>Burjkhalifa | Laxmmi Bomb | Akshay Kumar | Kiara Advani | Nikhita Gandhi | Shashi-Dj Khushi | Gagan</title>
            <uploadDate> 2020-10-18 </uploadDate>
            <views> 48.56M </views>    
            <likes> 0 </likes>
            <unlikes> 0 </unlikes>
            <comments> 2.22K </comments>
            <link> https://www.youtube.com/watch?v=a0TkeUhcVrM&amp;feature=emb_title&amp;ab_channel=ZeeMusicCompany </link>
        </BestVideo>
    </Channel>
    <Channel area="United States" language="Russian">
        <Name> Like Nastya </Name>
        <Rank> 9 </Rank>
        <Category>Entertainment</Category>
        <SignUpDate> 2016-12-06 </SignUpDate>
        <Subscribers> 63M </Subscribers>
        <TotalViews> 45.26B </TotalViews>
        <AverageViews> 41.23M </AverageViews>
        <Videos> 498 </Videos>
        <PotentialEarnings period="monthly" currency="$">
            <min>4.03M</min>
            <max>12.48M</max>
        </PotentialEarnings>
        <BestVideo>
            <title>Настя и папа веселятся вместе</title>
            <uploadDate> 2019-01-16 </uploadDate>
            <views> 397.97M </views>
            <likes> 369.14K </likes>
            <unlikes> 149.28K </unlikes>
            <comments> 0 </comments>
            <link> https://www.youtube.com/watch?v=r9AC5MEnKCs&amp;feature=emb_title&amp;ab_channel=LikeNastya </link>
        </BestVideo>
    </Channel>
    <Channel area="Brazil" language="Portuguese">
        <Name> Canal KondZilla </Name>
        <Rank> 10 </Rank>
        <Category>Music</Category>
        <SignUpDate> 2012-03-21 </SignUpDate>
        <Subscribers> 61.1M </Subscribers>
        <TotalViews> 32.42B </TotalViews>
        <AverageViews> 331.14K </AverageViews>
        <Videos> 1.58K </Videos>
        <PotentialEarnings period="monthly" currency="$">
            <min>345.63K</min>
            <max>1.2M</max>
        </PotentialEarnings>
        <BestVideo>
            <title>Old Town Road Funk: MC Jottapê e MC M10 feat. DJ RD - Sentou e Gostou (kondzilla.com)</title>
            <uploadDate> 2019-06-22 </uploadDate>
            <views> 188.4M </views>
            <likes> 388.38K </likes>
            <unlikes> 20.47K </unlikes>
            <comments> 9.74K </comments>
            <link> https://www.youtube.com/watch?v=p86_Aj8x014&amp;feature=emb_title&amp;ab_channel=CanalKondZilla </link>
        </BestVideo>
    </Channel>
    <Channel area="Canada" language="English">
